# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-30 16:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mocion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('asamblea', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='PlenoDerecho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votacion', models.PositiveSmallIntegerField()),
                ('mocion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yellowVoting.Mocion')),
                ('votante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yellowVoting.PlenoDerecho')),
            ],
        ),
    ]
