# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-30 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yellowVoting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plenoderecho',
            name='id',
        ),
        migrations.AddField(
            model_name='mocion',
            name='nombre',
            field=models.CharField(default='asd', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plenoderecho',
            name='codigo',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
    ]
