# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-30 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yellowVoting', '0002_auto_20160130_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voto',
            name='votacion',
            field=models.CharField(choices=[('A', 'En abstenci\xf3n'), ('B', 'En blanco'), ('C', 'En contra'), ('F', 'A favor')], max_length=1),
        ),
    ]
