# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-16 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yellowVoting', '0003_auto_20160130_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mocion',
            name='texto',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='voto',
            unique_together=set([('votante', 'mocion')]),
        ),
    ]
