# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-23 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yellowVoting', '0005_auto_20160422_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='mocion',
            name='grupo',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
