# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-29 16:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yellowVoting', '0006_mocion_grupo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('foto', models.ImageField(blank=True, null=True, upload_to=b'')),
                ('asamblea', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='VotoCandidato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votacion', models.CharField(choices=[('N', 'No confianza'), ('C', 'Confianza')], max_length=1)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos', to='yellowVoting.Candidato')),
                ('votante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yellowVoting.PlenoDerecho')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='votocandidato',
            unique_together=set([('votante', 'candidato')]),
        ),
    ]
