# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-29 17:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yellowVoting', '0007_auto_20161029_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voto',
            name='votante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos', to='yellowVoting.PlenoDerecho'),
        ),
        migrations.AlterField(
            model_name='votocandidato',
            name='candidato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votosCandidatos', to='yellowVoting.Candidato'),
        ),
        migrations.AlterField(
            model_name='votocandidato',
            name='votante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votosCandidatos', to='yellowVoting.PlenoDerecho'),
        ),
    ]
