# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-20 22:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(editable=False, max_length=64)),
                ('expaId', models.PositiveIntegerField(null=True, unique=True)),
                ('cedula', models.PositiveIntegerField(null=True, unique=True)),
                ('direccion', models.CharField(max_length=128, null=True)),
                ('telefono', models.CharField(max_length=32, null=True)),
                ('carrera', models.CharField(max_length=32, null=True)),
                ('fecha_nacimiento', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Universidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('direccion', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='persona',
            name='universidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='estudiantes', to='yellowDatabase.Universidad'),
        ),
        migrations.AddField(
            model_name='persona',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
