# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-20 22:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yellowDatabase', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='expaId',
            new_name='expaID',
        ),
    ]
