# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-20 22:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetaPrograma',
            fields=[
                ('programa', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('metaTotal', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MetaSemana',
            fields=[
                ('semana', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('meta', models.PositiveSmallIntegerField()),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metasSemanales', to='yellowAnalytics.MetaPrograma')),
            ],
        ),
    ]
