# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-20 22:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yellowAnalytics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metasemana',
            name='programa',
        ),
        migrations.DeleteModel(
            name='MetaSemana',
        ),
    ]
