# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-22 15:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yellowAnalytics', '0003_auto_20160120_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='LC',
            fields=[
                ('nombre', models.CharField(max_length=32, unique=True)),
                ('expaID', models.PositiveIntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='LogrosPrograma',
            fields=[
                ('programa', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('logros', models.PositiveSmallIntegerField()),
                ('lc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programas', to='yellowAnalytics.LC')),
            ],
        ),
        migrations.CreateModel(
            name='MC',
            fields=[
                ('nombre', models.CharField(max_length=32, unique=True)),
                ('expaID', models.PositiveIntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('nombre', models.CharField(max_length=32, unique=True)),
                ('expaID', models.PositiveIntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='mc',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mcs', to='yellowAnalytics.Region'),
        ),
        migrations.AddField(
            model_name='lc',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lcs', to='yellowAnalytics.MC'),
        ),
    ]
