# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-22 17:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yellowAnalytics', '0004_auto_20160122_1029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lc',
            old_name='pais',
            new_name='mc',
        ),
    ]
