# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-22 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yellowAnalytics', '0005_auto_20160122_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lc',
            name='nombre',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
