# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-22 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yellowAnalytics', '0006_auto_20160122_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='lc',
            name='igcdpMA',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='lc',
            name='igcdpRE',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='lc',
            name='igipMA',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='lc',
            name='igipRE',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='lc',
            name='ogcdpMA',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Matches OGCDP'),
        ),
        migrations.AddField(
            model_name='lc',
            name='ogcdpRE',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='lc',
            name='ogipMA',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='lc',
            name='ogipRE',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
