# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-29 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yellowAnalytics', '0009_auto_20160128_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='lc',
            name='total',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
