# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-06 01:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yellowAnalytics', '0014_auto_20160305_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='office_type',
            field=models.CharField(default='hey', max_length=8),
            preserve_default=False,
        ),
    ]
