# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-16 19:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yellowAnalytics', '0015_office_office_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='YearlyGoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MA', models.PositiveSmallIntegerField()),
                ('RE', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='office',
            name='scoreboard_enabled',
            field=models.BooleanField(default=False, verbose_name='Este campo representa si el scoreboard est\xe1 habilitado para esta entidad o no'),
        ),
        migrations.AddField(
            model_name='yearlygoal',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yearly_goals', to='yellowAnalytics.Office'),
        ),
        migrations.AddField(
            model_name='yearlygoal',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yearly_goals', to='yellowAnalytics.Program'),
        ),
        migrations.AlterUniqueTogether(
            name='yearlygoal',
            unique_together=set([('program', 'office')]),
        ),
    ]
