# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-23 14:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yellowAnalytics', '0016_auto_20160416_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='superoffice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suboffices', to='yellowAnalytics.Office'),
        ),
    ]
