# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-25 05:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yellowAnalytics', '0017_auto_20160723_0900'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('expaID', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='Expa ID')),
                ('name', models.CharField(help_text='El nombre compleeto del miembro', max_length=128, verbose_name='Nombre')),
                ('role', models.CharField(help_text='El rol que esa persona desempe\xf1a en la organizaci\xf3n', max_length=64, verbose_name='Rol')),
                ('phone', models.CharField(help_text='EL n\xfamero telef\xf3nico', max_length=32, verbose_name='Tel\xe9fono')),
                ('email', models.CharField(help_text='El correo electr\xf3nico', max_length=64, verbose_name='Correo')),
                ('alt_email', models.CharField(help_text='El correo electr\xf3nico', max_length=64, verbose_name='Correo alternativo')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member', to='yellowAnalytics.Office')),
            ],
        ),
    ]
