# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-25 05:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yellowAnalytics', '0018_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='yellowAnalytics.Office'),
        ),
    ]
