# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-25 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yellowAnalytics', '0019_auto_20160725_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='facebook',
            field=models.CharField(default=None, help_text='El facebook', max_length=32, verbose_name='Facebook'),
            preserve_default=False,
        ),
    ]
