# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-25 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yellowAnalytics', '0020_member_facebook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='facebook',
            field=models.CharField(help_text='El facebook', max_length=64, verbose_name='Facebook'),
        ),
    ]
