# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-25 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yellowAnalytics', '0021_auto_20160725_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='alt_email',
            field=models.CharField(help_text='El correo electr\xf3nico', max_length=64, null=True, verbose_name='Correo alternativo'),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.CharField(help_text='El correo electr\xf3nico', max_length=64, null=True, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='member',
            name='facebook',
            field=models.CharField(help_text='El facebook', max_length=64, null=True, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.CharField(help_text='EL n\xfamero telef\xf3nico', max_length=32, null=True, verbose_name='Tel\xe9fono'),
        ),
    ]
