# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 19:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yellowAnalytics', '0023_auto_20160725_2105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logrosprograma',
            old_name='MA',
            new_name='approved',
        ),
        migrations.RenameField(
            model_name='logrosprograma',
            old_name='RE',
            new_name='realized',
        ),
    ]
