# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 23:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yellowAnalytics', '0024_auto_20160918_1444'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthlygoal',
            old_name='MA',
            new_name='approved',
        ),
        migrations.RenameField(
            model_name='monthlygoal',
            old_name='RE',
            new_name='realized',
        ),
    ]
