# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 14:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yellowAnalytics', '0026_auto_20160918_1902'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyAchievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField()),
                ('approved', models.PositiveSmallIntegerField(null=True)),
                ('realized', models.PositiveSmallIntegerField(null=True)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_achievements', to='yellowAnalytics.Office')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_achievements', to='yellowAnalytics.Program')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='monthlyachievement',
            unique_together=set([('month', 'program', 'office')]),
        ),
    ]
