# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-10 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yellowAnalytics', '0027_auto_20160920_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlygoal',
            name='year',
            field=models.PositiveSmallIntegerField(default=2016),
            preserve_default=False,
        ),
    ]
