# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-04 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yellowAnalytics', '0029_auto_20161010_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='logrosprograma',
            name='completed',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
