# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-03-23 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yellowAnalytics', '0030_logrosprograma_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlygoal',
            name='completed',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
